version: "3.7"
services:
  ejabberd:
    image: rroemhild/ejabberd
    volumes:
      - ./docker/conf/:/opt/ejabberd/conf/
    ports:
      - 5222:5222
      - 5269:5269
      - 5280:5280
    environment:
      - ERLANG_NODE=ejabberd
      - EJABBERD_ADMINS=admin@localhost
      - EJABBERD_USERS=admin@localhost:passw0rd 24988435539@localhost:passw0rd 21998859705@localhost:passw0rd
      - TZ=America/Sao_Paulo
      - EJABBERD_STARTTLS=false
